name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install make

      - name: Build package
        run: make build

      - name: Go vet
        run: make vet

      - name: Start server
        run: make run-ci

      - name: Run e2e tests
        run: make test-e2e
